const {
  editFile
} = require(
  "./core/safe-editor"
);

async function test() {

  const result =
    await editFile(
      "sandbox/generated.md",
      "Generated by AI",
      "Updated safely by AI"
    );

  console.log(result);
}

test();
